services:
  word2pdf:
    build: .
    environment:
      API_KEY: ${API_KEY}
    ports:
      - "8090:8090"
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
    mem_limit: 1g
    cpus: 1.0